services:
  web:
    build:
      context: .
      dockerfile: services/web/Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      FLASK_SECRET_KEY: "${FLASK_SECRET_KEY:-change-me}"
      AI_BASE_URL: "http://ai:9001"
      SQLITE_PATH: "/app/data/app.db"
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - ai
    restart: unless-stopped

  ai:
    build:
      context: .
      dockerfile: services/ai/Dockerfile
    expose:
      - "9001"
    env_file: .env
    environment:
      OLLAMA_URL: "http://ollama:11434"
      LLM_MODEL: "${LLM_MODEL:-llama3:mini}"
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"   # optional; keep internal-only by removing this mapping
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: ["/bin/sh","-lc","/usr/bin/ollama serve & sleep 3 && ollama pull ${LLM_MODEL:-llama3:mini} && wait"]

volumes:
  sqlite_data:
  ollama_models:
